### ISSUE TITLE
Terms link on Reg Form

### ISSUE THREAD

**Issue by celiaramsay** [larktraditionalarts/chaplin-child#18]
The Terms Link on the reg form still links to the old html page, not your new and shiny one!
![Screen Shot 2020-02-13 at 10 37 15 AM](https://user-images.githubusercontent.com/1187196/74466994-23e6d480-4e4d-11ea-865b-3cfbcd3a010d.png)

**Comment by willfulbard** [comment]
I can't change this until the new site goes live

**Comment by celiaramsay** [comment]
You may not have had time to work on this AMAZING WEBSITE, but just in case, I'm adding this to the thread; link to "terms of reg" on reg form - no change
![Screen Shot 2020-02-13 at 10 39 27 PM](https://user-images.githubusercontent.com/1187196/74509472-70b2c580-4eb6-11ea-97d6-807b8e73e779.png)
