### ISSUE TITLE
Add times to period in Workshop schedule grid

### ISSUE THREAD

**Issue by celiaramsay** [larktraditionalarts/chaplin-child#24]
For ease of use, add workshop times in an additional row below period headings, rinse and repeat for each of the three camp grids. The workshop times are:

Period 1: 9:30 – 10:30
Period 2: 10:45 – 11:45
Period 3: 12:30 – 1:30
Period 4: 1:45 – 2:45
Period 5: 3:00 – 4:00
Period 6: 4:15 – 5:15
Period 7: 5:30 – 6:30: 

![Screen Shot 2020-02-17 at 3 05 34 PM](https://user-images.githubusercontent.com/1187196/74691792-0f7e4100-5199-11ea-9a95-ede6812ddaa7.png)

**Comment by willfulbard** [comment]
I just did this!   See https://github.com/larktraditionalarts/chaplin-child/issues/21
