### ISSUE TITLE
Workshop search page - Camp category not working

### ISSUE THREAD

**Issue by celiaramsay** [larktraditionalarts/chaplin-child#31]
On the Workshop Search page, when you select Camp, as a limiting category, it removes the workshops from view. So, for example, you go from this: 

![Screen Shot 2020-02-19 at 12 33 13 PM](https://user-images.githubusercontent.com/1187196/74873434-0cf42680-5314-11ea-9896-39649c194a29.png)

to this:

![Screen Shot 2020-02-19 at 12 33 56 PM](https://user-images.githubusercontent.com/1187196/74873497-285f3180-5314-11ea-9f3a-38bda3e462eb.png)

**Comment by willfulbard** [comment]
This is a great ticket, all the relevant details and a step-by-step on how to reproduce the error!
