### ISSUE TITLE
Locate "black background" shirts for Celia to change

### ISSUE THREAD

**Issue by celiaramsay** [larktraditionalarts/chaplin-child#43]
I can't find them...can you tell me which ones specifically (by 2020 and description)?

**Comment by willfulbard** [comment]
2020 Kids Sizes – Short Sleeve T-Shirt:

https://www.larkcamp.org/product/2020-1st-pandemic-year-youth-short-sleeve-t-shirt-with-woodlands-wildlife-misses-us-available-in-black-only/

2020 Kids Sizes – Pullover Hoodie (image on front):

https://www.larkcamp.org/product/2020-1st-pandemic-year-kids-hoodie-with-woodlands-wildlife-misses-us-on-the-front-available-in-black-only/

**Comment by celiaramsay** [comment]
Thanks – I deleted the image and replaced it. I can't see what was wrong, but there was a difference in resolution, so hopefully all better.
