### ISSUE TITLE
Restyle workshop schedule for desktop

### ISSUE THREAD

**Issue by willfulbard** [larktraditionalarts/chaplin-child#9]
https://drive.google.com/open?id=1ZT4yFQs4cuaNcZ88jlOwrQ27lKzWQTWW

It's organized the same as you have it currently, I just used some blocks+lines+color to separate the kinds of information. I also used a gold line with a little caption up top to indicate where the lunch break is, i feel like color here could be a quick way to demarcate that time in the schedule. Also i have the location rows alternating white/grey to just make it quick to trace back to where each workshop would be. I think overall this is just like restyling the existing schedule! 

For the desktop view, i think the period times could be smaller underneath the "period #" headers if so.

hex codes for the greys:
- dark grey vertical lines #B3B3B3
- light grey row backgrounds: #F4F4F4

**Comment by simonlace** [comment]
One more thing, to exit out of the clickable workshop information popup, it seems intuitive to also be ale to click outside of the popup to exit in addition to clicking the X in the upper right hand corner

**Comment by willfulbard** [comment]
> One more thing, to exit out of the clickable workshop information popup, it seems intuitive to also be ale to click outside of the popup to exit in addition to clicking the X in the upper right hand corner

@simonlace - I moved this to a new issues, since it can be solved separate from the re-design.
